openapi: 3.0.0
servers:
  - url: 'https://cryptonomic.tech/conseil'
    description: Pre-alpha deployment
info:
  description: Specification for Conceil - a RESTful API for Tezos.
  version: 0.0.1
  title: Conceil
  termsOfService: ''
  contact:
    email: api@cryptonomic.tech
    name: Vishakh
    url: 'https://cryptonomic.tech'
  license:
    name: Apache-2.0
    url: 'https://opensource.org/licenses/Apache-2.0'
tags:
  - name: blocks
    description: Information about blocks.
  - name: accounts
    description: 'Information, creation and modifications of accounts.'
  - name: operations
    description: Information and creation of operations.
paths:
  '/tezos/{networkid}/blocks':
    get:
      tags:
        - blocks
      summary: All available blocks on the given network.
      responses:
        default:
          description: Default response
      parameters: []
      operationId: getAllBlocks
  '/tezos/{networkid}/blocks/{blockid}':
    get:
      tags:
        - blocks
      summary: Information about a given block.
      parameters:
        - name: blockid
          in: path
          description: ID of block to return
          required: true
          schema:
            type: string
            format: string
      responses:
        default:
          description: Default response
  '/tezos/{networkid}/blocks/head':
    get:
      tags:
        - blocks
      summary: Information about the block head.
      responses:
        default:
          description: Default response
      parameters: []
  '/tezos/{networkid}/operations/{operationid}':
    get:
      tags:
        - operations
      summary: Information about a given operation.
      parameters:
        - name: operationid
          in: path
          description: ID of operation to return
          required: true
          schema:
            type: string
            format: string
      responses:
        default:
          description: Default response
  '/tezos/{networkid}/operations':
    get:
      tags:
        - operations
      summary: All available operations.
      responses:
        default:
          description: Default response
      parameters: []
    post:
      tags:
        - operations
      summary: transaction
      parameters:
        - name: amount
          in: query
          required: true
          schema:
            type: integer
          description: 'amount to send, in tez'
        - name: destination
          in: query
          required: true
          schema:
            type: string
          description: to which contract ID
        - name: parameter
          in: query
          required: false
          schema:
            type: object
          description: Michelson program parameters
      operationId: ''
      responses:
        default:
          description: Default response
  '/tezos/{networkid}/accounts':
    get:
      tags:
        - accounts
      summary: returns list of accounts
      parameters: []
      operationId: ''
      responses:
        default:
          description: Default response
    post:
      tags:
        - accounts
      summary: creates a new account
      parameters:
        - name: managerPubkey
          in: query
          required: true
          schema:
            type: string
          description: manager's account ID
        - name: balance
          in: query
          required: true
          schema:
            type: string
          description: funding amount
        - name: spendable
          in: query
          required: false
          schema:
            type: string
          description: is it spendable?
        - name: delegatable
          in: query
          required: false
          schema:
            type: string
          description: 'is it delegatable? '
        - name: delegate
          in: query
          required: false
          schema:
            type: string
          description: the delegate's account ID
        - name: script
          in: query
          required: false
          schema:
            type: string
          description: code and storage
      operationId: ''
      responses:
        default:
          description: Default response
  '/tezos/{networkid}/accounts/{accountid}':
    get:
      tags:
        - accounts
      summary: returns account information
      parameters: []
      operationId: ''
      responses:
        default:
          description: Default response
  '/tezos/{networkid}/accounts/{accountid}/delegate':
    get:
      tags:
        - accounts
      summary: returns delegate for the account
      parameters: []
      operationId: ''
      responses:
        default:
          description: Default response
    put:
      tags:
        - accounts
      summary: sets delegate for account
      parameters:
        - name: delegate
          in: query
          required: true
          schema:
            type: string
          description: the delegate for account
      operationId: ''
      responses:
        default:
          description: Default response
security:
  - newSecurityScheme: []
components:
  links: {}
  callbacks: {}
  schemas: {}
  securitySchemes:
    newSecurityScheme:
      type: apiKey
      name: apiKey
      in: query
